- name: varaibles from file
  hosts: localhost
  vars_files:
    - variables.yaml
  tasks:
  - name: print variables
    ansible.bultin.debug:
      msg: " Course is {{Course}}, Trainer is {{Trainer}}, Duration {{Duration}}"
