#ansible-playbook -i inventory  -e ansible_user=centos -e ansible_password=DevOps321 cart.yaml
- name:
  hosts: cart
  become: yes
  tasks:
  - name: disbale exising node js and enable js18 version
    shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
    
  - name: install node js
    dnf:
      name: nodejs
      state: present
  
  - name: create roboshop user
    user:
      name: roboshop
  
  - name: create directory
    file:
      path: app
      state: directory

  - name: dowload cart code
    get_url: 
      url: https://roboshop-builds.s3.amazonaws.com/cart.zip
      dest: /tmp
  
  - name: unzip cart code
    unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: install dependencied using npm
    community.general.npm:
      path: /app

  - name: copy cart service
    copy:
      src: cart.service
      dest : /etc/systemd/system/cart.service

  - name: daemon reload
    systemd_service:
      daemon_reload: true
  
  - name: restart the service
    service:
      name: cart
      state: restarted
      enabled: yes

    

