#ansible-playbook -i inventory  -e ansible_user=centos -e ansible_password=DevOps321 cart.yaml
- name:
  hosts: cart
  become: yes
  tasks:
  - name:
    shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
    
  - name:
    dnf:
      name: nodejs
      state: present
  
  - name:
    user:
      name: roboshop
  
  - name:
    file:
      path: /app
      state: directory

  - name:
    get_url: 
      url: https://roboshop-builds.s3.amazonaws.com/cart.zip
      dest: /tmp
  
  - name:
    unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: 
    community.general.npm:
      path: /app

  - name:
    copy:
      src: cart.service
      dest : /etc/systemd/system/cart.service

  - name:
    systemd_service:
      daemon_reload: true
  
  - name:
    service:
      name: cart
      state: restarted
      enabled: yes

    

