#ansible-playbook -i 172.31.86.60, -e ansible_user=centos -e ansible_password=DevOps321 catalogue.yaml


- name: setting up catalogue server
  hosts: 172.31.86.60
  become: yes
  tasks:
  - name: disable existing node js vesion and enable node js version 18
    shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  # - name: 
  #   command: dnf module disable nodejs -y
  # - name: 
  #   command: dnf module enable nodejs:18 -y

