- name:
  hosts: mysql
  become: yes
  tasks:
  - name:
    command: dnf module disable mysql -y
  - name:
    dnf:
      name: mysql-community-server
      state: pressent
  
  - name:
    service:
      name: mysqld
      state: started
      enabled: yes
  
  - name:
    command: mysql_secure_installation --set-root-pass RoboShop@1

  - name: 
    commad: mysql -uroot -pRoboShop@1