# ansible-playbook -i inventory  -e ansible_user=centos -e ansible_password=DevOps321 mysql.yaml

- name:
  hosts: mysql
  become: yes
  tasks:
  - name:
    command: dnf module disable mysql -y
  - name:
    dnf:
      name: mysql-community-server
      state: present
  
  - name:
    service:
      name: mysqld
      state: started
      enabled: yes
  
  - name:
    command: mysql_secure_installation --set-root-pass RoboShop@1

  - name: 
    command: mysql -uroot -pRoboShop@1