#ansible-playbook -i inventory redis -e ansible_user=centos -e ansible_password=DevOps321 redis.yaml

- name:
  hosts: redis
  become: yes
  tasks:
  # - name: Install the redis rpm from a remote repo
  #   dnf:
  #     name: 'https://rpms.remirepo.net/enterprise/remi-release-8.rpm'
  #     state: present

# - name: Install Apache >= 2.4
#   ansible.builtin.dnf:
#     name: httpd >= 2.4
#     state: present

  - name: install remi rereleasepo
    command: dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y


  - name: install remi repo
    command: dnf module enable redis:remi-6.2 -y

  - name: install redis
    dnf:
      name: redis
      state: present

  - name: enable remote access
    replace:
      path: /etc/redis/redis.conf
      regexp: "127.0.0.1"
      replace: "0.0.0.0"

  - name: restart redis
    service:
      name: redis
      state: restarted
      enabled: yes

