# ansible-playbook -i inventory  -e ansible_user=centos -e ansible_password=DevOps321 shipping.yaml
- name:
  hosts: shipping
  vars:
    pwd: RoboShop@1
  become: yes
  tasks:
  - name: install maven
    dnf:
      name: maven
      state: present

  - name: create user roboshop
    user:
      name: roboshop

  - name: create app directory
    file:
      path: /app
      state: directory

  - name: download the code
    get_url:
      url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
      dest: /tmp
  
  - name: unzip the code
    unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name:  build package
    command: mvn clean package
    args:
      chdir: /app
  - name:
    command: mv /app/target/shipping-1.0.jar shipping.jar

  - name: cipying the shipping service file
    copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  
  - name: daemon reload
    systemd_service:
      daemon_reload: true

  - name: start shipping server
    service:
      name: shipping
      state: started
      enabled: yes

  - name: install my sql client
    dnf:
      name: mysql
      state: present

############need to uncomment this###########

  - name: load shipping schema
    shells: "mysql -h mysql.nariops.online -uroot -p{{pwd}} < /app/schema/shipping.sql"
  
  - name: restart shipping server
    service:
      name: shipping
      state: restarted
      





