#ansible-playbook -i inventory  -e ansible_user=centos -e ansible_password=DevOps321 user.yaml

- name: settring up user application
  hosts: user
  become: yes
  tasks:
  - name:
    shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name:
    dnf:
      name: nodejs
      state: present
  - name:
    user:
      name: roboshop

  - name:
    file:
      path: /app
      state: directory
  
  - name:
    get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp

  - name:
    unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name:
    community.general.npm:
      path: /app

  - name:
    copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name:
    service:
      name: user
      state: restarted
      enabled: yes
