#ansible-playbook -i inventory  -e ansible_user=centos -e ansible_password=DevOps321 user.yaml

- name: settring up user application
  hosts: user
  become: yes
  tasks:
  - name:
    shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: install node js
    dnf:
      name: nodejs
      state: present
  - name: create user
    user:
      name: roboshop

  - name: create app directory
    file:
      path: /app
      state: directory
  
  - name: dowload user appliaction code
    get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp

  - name: Unzip the code
    unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: resolve the dependencies
    community.general.npm:
      path: /app

  - name: copy user service file
    copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: deamon realod and start
    systemd_service: 
      daemon_reload: true

  - name: restart the user service
    service:
      name: user
      state: restarted
      enabled: yes
