- name:
  hosts: web
  become: yes
  tasks:
  - name:
    dnf: nginx
      state: present
  - name: Remove file (delete file)
    file:
      path: /usr/share/nginx/html/*
      state: absent
  - name:
    get_url: 
      url: https://roboshop-builds.s3.amazonaws.com/web.zip
      path: /tmp
  - name:
    unarchive:
      src: /tmp/web.zip
      dest: /usr/share/nginx/html
      remote_src: yes
  - name:
    copy:
      src: roboshop.conf
      dest: /etc/nginx/default.d/roboshop.conf 
  - name:
    service:
      name: nginx
      state: restarted